# Project: ch04
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o 副本.o
LINKOBJ  = main.o 副本.o
LIBS     = -L"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib32" -L"E:/MyDownloads/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = ch04.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

副本.o: 副本.cpp
	$(CPP) -c 副本.cpp -o 副本.o $(CXXFLAGS)
